//! Turn `shaders/*.rs` into serialized Naga modules under `OUT_DIR`.
//!
//! The same sources are compiled as Rust by the crate. This step is what the
//! GPU actually runs: each module is `include_bytes!`'d into the library and
//! handed to blade-graphics as IR.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo::rerun-if-changed=shaders");
    println!("cargo::rerun-if-env-changed=PROFILE");

    let caps = blade_caps();
    let config = config_source();
    let mut failed = false;
    let mut compiled: Vec<(&str, Vec<u8>)> = Vec::new();
    for shader in SHADERS {
        let preludes: Vec<String> = shader
            .preludes
            .iter()
            .map(|name| {
                if *name == "config" {
                    config.clone()
                } else {
                    std::fs::read_to_string(Path::new("shaders").join(format!("{name}.rs")))
                        .unwrap_or_else(|err| panic!("read shaders/{name}.rs: {err}"))
                }
            })
            .collect();
        let source_path = PathBuf::from("shaders").join(format!("{}.rs", shader.module));
        let source = match std::fs::read_to_string(&source_path) {
            Ok(source) => source,
            Err(err) => {
                println!("cargo::error=read {}: {err}", source_path.display());
                failed = true;
                continue;
            }
        };
        match compile(&source_path, &preludes, &source, caps) {
            Ok(bytes) => compiled.push((shader.module, bytes)),
            Err(err) => {
                failed = true;
                for line in err.lines() {
                    println!("cargo::error={line}");
                }
            }
        }
    }
    if failed {
        std::process::exit(1);
    }

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let mut generated = String::from(
        "// Generated by build.rs. Do not edit.\n\
         // Each constant is a Naga module serialized as JSON.\n\n",
    );
    let mut all = Vec::new();
    for (module, bytes) in &compiled {
        let file_name = format!("{module}.json");
        std::fs::write(out_dir.join(&file_name), bytes).expect("write shader IR");
        let constant = module.to_ascii_uppercase();
        writeln!(
            generated,
            "pub const {constant}: &[u8] = include_bytes!({file_name:?});"
        )
        .unwrap();
        all.push(format!("({module:?}, {constant})"));
    }
    writeln!(
        generated,
        "\npub const ALL: &[(&str, &[u8])] = &[{}];",
        all.join(", ")
    )
    .unwrap();
    std::fs::write(out_dir.join("shader_ir.rs"), generated).expect("write shader_ir.rs");
}

struct Shader {
    module: &'static str,
    preludes: &'static [&'static str],
}

const SHADERS: &[Shader] = &[
    Shader {
        module: "noop",
        preludes: &[],
    },
    Shader {
        module: "env_prepare",
        preludes: &[],
    },
    Shader {
        module: "debug_blit",
        preludes: &[],
    },
    Shader {
        module: "debug_draw",
        preludes: &["config", "quaternion", "debug", "camera"], // quaternion before camera: camera calls qrot
    },
    Shader {
        module: "post_proc",
        preludes: &["config", "debug", "color", "debug_param"],
    },
    Shader {
        module: "skin",
        preludes: &["config", "vertex", "skin_inc"],
    },
    Shader {
        module: "raster",
        preludes: &["config", "vertex", "brdf", "color", "skin_inc"],
    },
    Shader {
        module: "a_trous",
        preludes: &["config", "quaternion", "camera", "gbuf", "surface"],
    },
    Shader {
        module: "fill_gbuf",
        preludes: &[
            "config",
            "vertex",
            "quaternion",
            "camera",
            "debug_param",
            "debug",
            "brdf",
            "gbuf",
            "hit",
        ],
    },
    Shader {
        module: "path_trace",
        preludes: &[
            "config",
            "vertex",
            "quaternion",
            "random",
            "camera",
            "debug_param",
            "brdf",
            "sampling",
            "env_importance",
            "hit",
            "env_light",
        ],
    },
    Shader {
        module: "ray_trace",
        preludes: &[
            "config",
            "vertex",
            "quaternion",
            "random",
            "camera",
            "debug_param",
            "debug",
            "brdf",
            "sampling",
            "env_importance",
            "surface",
            "gbuf",
            "hit",
            "env_light",
        ],
    },
];

fn config_source() -> String {
    let debug = std::env::var("PROFILE").ok().as_deref() != Some("release");
    std::fs::read_to_string("shaders/config.rs")
        .expect("config")
        .replace(
            "cfg!(debug_assertions)",
            if debug { "true" } else { "false" },
        )
}

fn blade_caps() -> synaga::naga::valid::Capabilities {
    use synaga::naga::valid::Capabilities as C;
    C::RAY_QUERY
        | C::STORAGE_BUFFER_BINDING_ARRAY
        | C::STORAGE_BUFFER_BINDING_ARRAY_NON_UNIFORM_INDEXING
        | C::TEXTURE_AND_SAMPLER_BINDING_ARRAY
        | C::TEXTURE_AND_SAMPLER_BINDING_ARRAY_NON_UNIFORM_INDEXING
}

fn compile(
    path: &Path,
    preludes: &[String],
    source: &str,
    caps: synaga::naga::valid::Capabilities,
) -> Result<Vec<u8>, String> {
    let texts: Vec<&str> = preludes
        .iter()
        .map(String::as_str)
        .chain(std::iter::once(source))
        .collect();
    let module = synaga::parse_all(texts).map_err(|err| {
        let file = preludes
            .get(err.index)
            .map(|_| "prelude")
            .unwrap_or("shader");
        format!("{}: {file}: {}", path.display(), err.error)
    })?;
    let flags = synaga::naga::valid::ValidationFlags::all()
        ^ synaga::naga::valid::ValidationFlags::BINDINGS;
    synaga::validate_with(&module, flags, caps)
        .map_err(|err| format!("{}: {err}", path.display()))?;
    serde_json::to_vec(&module).map_err(|err| format!("{}: {err}", path.display()))
}
